#include <stdio.h>
#include "pico/stdlib.h"
#include "hardware/i2c.h"

// Include our drivers
#include "si5351.h"
#include "i2s_rx.pio.h" // This is auto-generated by CMake!

int main() {
    stdio_init_all();

    while (true) {
        printf("SDR Receiver compiler test successful!\n");
        sleep_ms(1000);
    }
    
    return 0;
}